### ISSUE TITLE
[Question] What SequenceResolver we should use? Does 'RandomSequenceResolver' is a good choice

### ISSUE THREAD

**Issue by vanthao03596** [godruoyi/php-snowflake#11]

**Comment by godruoyi** [comment]
Normally, using the default RandomSequenceResolver will work fine, but if your business has high concurrency requirements and needs to strictly ensure that the IDs obtained for each request are not consistent, you may need to customize SequenceResolver.

like, Using the incr atomic operation of redis to generate ID.
