### ISSUE TITLE
重复生成ID

### ISSUE THREAD

**Issue by jilangsanqian** [godruoyi/php-snowflake#13]
![image](https://user-images.githubusercontent.com/7589236/85421849-7c6e7100-b5a7-11ea-9372-7994a1815bde.png)
用 ab -c 200  -n 10000 http://127.0.0.1:18306/test/id
至少有三分之一的重复ID生成.老兄这是怎么回事?

**Comment by godruoyi** [comment]
最近在医院，很抱歉才回复你。

从截图可看出你可能使用的是传统的 FPM 形式；这种模式下，每个 HTTP 请求都对于一个单独的进程，而你在每个进程里都使用的是 new Snowflake 然后生成 ID。这可能导致在并发情况下，生成雪花ID的时间差值是一样的，故生成的雪花ID也是一样的。

针对这种情况，你可以使用下面两种方式：

1. 用 Package 内在的 RedisSequenceResolver
2.采用类似 Swoole 的形式，生成雪花ID的对象保存为全局变量，每个子进程「或协程」共享该变量生成ID。

```php
$redis = new \Redis();
$redis->connect('127.0.0.1', 6379);

$snowflake = new \Godruoyi\Snowflake\Snowflake;
$snowflake->setSequenceResolver(new RedisSequenceResolver($redis));

```

**Comment by jilangsanqian** [comment]
好的。多谢！明白错在哪儿了。祝身体安康

**Comment by okool** [comment]
就这样解决?随机数都比你这个ID生成器强吧

**Comment by godruoyi** [comment]
@okool 很抱歉给你这样的体验，但我觉得你可能没理解这样使用为什么会出现重复的问题。

```
for($i=0; $i<100000; $i++){
    $key = (new Snowflake())->id();
    $ids[$key] = 1;
}
```
因为默认情况会采用随机 ID 生成器，而这里每次循环都是重新初始化一个实例，你循环 10w 次就是 10w 个不同的实例，10w 个实例在生产 ID 时，如果时间差一样，序列号又可很是 0时，又怎么不回生成重复的 ID 呢。

所以上面才建议可以使用 Redis 作为共享内存使用全局序列号来确保唯一。

当然你也提出了个问题，我会增加一个 FileLock 以及基于信号量的 Resolver 来解决并发情况下大量不同对象生成相同 ID 的问题。

最后，与人为善，比聪明更重要。

**Comment by resnou** [comment]
@godruoyi 你好，我看到你 #37 这里修复了sequence一直为0的情况，是不是代表着题主这种情况已经部分解决了？
虽然还会存在在高并发情况下可能会导致生成的 ID 重复的情况，但不会出现题主这种大量重复的情况？

**Comment by godruoyi** [comment]
@resnou 谢谢你的提问，我刚刚修复了一个 [bug](https://github.com/godruoyi/php-snowflake/pull/39)。

是的，默认的随机算法不保证生成唯一的 ID，目前测试 10w 次循环大约可生成 9.5 无重复的 ID。

```
public function testBatchForDiffInstance()
{
    $ids = [];
    $count = 100000; // 10w

    for ($i = 0; $i < $count; $i++) {
        $ids[(new Snowflake())->id()] = 1;
    }

    $this->assertNotCount($count, $ids);
    $this->assertGreaterThan(90000, count($ids)); // 95489
}
```

**Comment by resnou** [comment]
@godruoyi 谢谢，我说呢，看你2.1.0生成了随机sequence，测试后发现并没有，sequence还是全为0，
更新了2.1.1，`ab -c 200 -n 100000`测试，10万条数据，去重后95715条，与你测试的基本一样，不过因为随机生成sequence，所以产生的id并不是递增的，建议在文档中标注一下，防止出现使用上的问题。

**Comment by godruoyi** [comment]
thank u, 其实也是递增的，因为时间在增加，生成的 ID 也会递增。
