### ISSUE TITLE
一个奇怪的问题会生成负数

### ISSUE THREAD

**Issue by zeroone2005** [godruoyi/php-snowflake#14]
一个奇怪的问题会生成负数，2台电脑一台不会生成负数，一台很大几率会产生负数

**Comment by godruoyi** [comment]
你好，你是怎么调用的呢，能贴下相关代码不，然后介绍下

- PHP 版本
- 操作系统

等等信息

**Comment by zeroone2005** [comment]
操作系统：win10 专业版 
PHP:  7.1.13

`
$snowflake= new \Godruoyi\Snowflake\Snowflake();
for($i = 1; $i < 1000; $i++) {
    echo $snowflake->id() , '<br/>';
}
`

**Comment by godruoyi** [comment]
我这边按你的测试案例没复现这个问题

```php
public function testBasic()
{
    $snowflake = new \Godruoyi\Snowflake\Snowflake();

    for ($i = 1; $i < 1000; $i++) {
        // echo $snowflake->id() , "\r\n";
        if ($snowflake->id() <= 0) {
            $this->assertTrue(false);
        }
    }

    $this->assertTrue(true);
}
```

这是测试结果

![image](https://user-images.githubusercontent.com/16079222/89022525-c429aa80-d354-11ea-88e9-52d6b1f97f2d.png)

你能可以尝试以下检查后重试呢：

- 检查系统时间是否正常

或者通过 `$snowflake->setStartTimeStamp(strtotime('2019-08-08')*1000);` 手动设置开始时间

- 更新 SDK 到最新版本
