### ISSUE TITLE
getCurrentMicrotime in 1 second may  return samme value 

### ISSUE THREAD

**Issue by ArtistLu** [godruoyi/php-snowflake#16]
getCurrentMicrotime in 1 second may  return samme value , id() functino while loop usleep(1) have meaning？

**Comment by godruoyi** [comment]
Hello

Although `getCurrentMicrotime` may return the same time, but when `callResolver` method is called, 

the millisecond value of the current time is passed to SequenceResolver for processing.

The processing logic that SequenceResolver needs to guarantee is as follows (eg. RandomSequenceResolver)

```php
public function sequence(int $currentTime)
{
    if ($this->lastTimeStamp === $currentTime) {
        ++$this->sequence;

        return $this->sequence;
    }

    $this->sequence = 0;
    $this->lastTimeStamp = $currentTime;

    return 0;
}
```

Assigns the current time to a global variable, and returns the sequence + 1 if the timestamp is the same on the next calculation.

However, sequence cannot be incremented infinitely, and its maximum value cannot exceed 2^MAX_SEQUENCE_LENGTH - 1.

```php
public function id()
{
    $currentTime = $this->getCurrentMicrotime();
    while (($sequence = $this->callResolver($currentTime)) > (-1 ^ (-1 << self::MAX_SEQUENCE_LENGTH))) {
        usleep(1);
        $currentTime = $this->getCurrentMicrotime();
    }
    ...
}
```

So in the `id` method, when the returned sequence >= 2^MAX_SEQUENCE_LENGTH - 1, the program sleeps 1us to ensure that the `callResolver` method is called use the next microsecond.

**Comment by godruoyi** [comment]
And maybe you can find some useful information here https://github.com/godruoyi/php-snowflake/issues/9 .

**Comment by ArtistLu** [comment]
大佬你好，开始我以为你是外国人。我有个疑惑，希望能够解答。就是在自己实现sequence函数的时候，用户就一定会保证你给的逻辑吗？因为我们项目上sequence返回值是一直在增大的。导致大到4095会在id()函数中出现死循环。是不是应该在文档中把sequence函数自我实现情况特别说明下？当然我不知道是不是我没有仔细看文档。
