### ISSUE TITLE
生成的id都是一样的

### ISSUE THREAD

**Issue by zhengyingming** [godruoyi/php-snowflake#17]
for($i=1;$i<=10;$i++)
{
   $snowflake = new \Godruoyi\Snowflake\Snowflake1, 1);
   $snowflake->setStartTimeStamp($time);
   $snowflake->setSequenceResolver(new RandomSequenceResolver());
   return $snowflake->id();
}
生成的id都是一样的

**Comment by godruoyi** [comment]
Please see https://github.com/godruoyi/php-snowflake/issues/13.
