### ISSUE TITLE
setStartTimeStamp not working.

### ISSUE THREAD

**Issue by rickmartensnl** [godruoyi/php-snowflake#18]
I don't know how but it doesn't continue after setStartTimeStamp() function. Anyone know how to resolve?
```php
$snowflake = new Godruoyi\Snowflake\Snowflake;
echo "seven";
try {
       $snowflake->setStartTimeStamp(strtotime('2019-09-09')*1000);
       echo $snowflake->getStartTimeStamp();
} catch (Exception $exception) {
       echo $exception;
}

echo "four";
$id = $snowflake->id();
echo $id;
```

**Comment by rickmartensnl** [comment]
When I do this:

```php
        $snowflake = new Godruoyi\Snowflake\Snowflake;
        echo "seven";
        try {
            $start = strtotime('2019-09-09')*1000;
            $snowflake->setStartTimeStamp((int) $start);
            echo $snowflake->getStartTimeStamp();
        } catch (Exception $exception) {
            echo $exception;
        }

        echo "four";
        $id = $snowflake->id();
        echo $id;
```

I get this exception: `Exception: The maximum time length is 2^41, You can reset the start time to fix this`. Don't know what is wrong with it.

**Comment by rickmartensnl** [comment]
Apparently it is only an issue on my web server and not on my 64-bit localhost. Please fix it.

**Comment by godruoyi** [comment]
When this exception happens.

`Exception: The maximum time length is 2^41, You can reset the start time to fix this`

It means:

```php
$your_server_current_microtime - $your_set_start_timestamp > 2^41 // the maximum time limit allowed by the snowflake algorithm
```

**so maybe you can check you server times are correct.**

And it's passed on my server.

![image](https://user-images.githubusercontent.com/16079222/96393651-545beb00-11f2-11eb-809a-f779922c7ab8.png)

**Comment by rickmartensnl** [comment]
I changed my hole system to do generate snowflakes on MySQL my server hosting is only 32bit.

**Comment by godruoyi** [comment]
Sorry, I don't understand what the snowflake algorithm has to do with mysql? And it has nothing with the number of computer bits. So if you still can't work, please check your server time again!

**Comment by rickmartensnl** [comment]
It had to do with the bits of the system. Because amount of bits of the system tells you the maximum hight of an integer that is 2^32 and with that you can't generate a snowflake of a length of 64 bits.

**Comment by rickmartensnl** [comment]
About the time zone, it's the same. I live in the Netherlands and my server is in Germany. Same time zone.

**Comment by godruoyi** [comment]
Sorry, I hadn't thought of that, thanks for the heads up.

At the moment we don't intend to support 32-bit operating systems, because to run properly on 32-bit systems we would have to set MAX_TIMESTAMP_LENGTH = 32.

When the maximum timestamp length of the snowflake algorithm is 32 bits, it means that its maximum time difference value is -1 ^ (-1 << 31) = 2147483647 microseconds.

```bash
>>> -1 ^ (-1 << 31)
=> 2147483647    // microseconds
>>>
>>>
>>>
>>> (-1 ^ (-1 << 31)) / (1000 * 24 * 60 * 60)
=> 24.855134803241 // convert to days
>>>
```
which would mean that the snowflake algorithm would work properly for up to 24 days, It's too short which we cannot allow.

**Comment by rickmartensnl** [comment]
Somebody said to me that it might be an idea to split the snowflake into 2 integers and then put them together as a string.

**Comment by godruoyi** [comment]
Maybe that's a better way, and if you know how to make it, let me know.
