### ISSUE TITLE
how to use it in lumen?

### ISSUE THREAD

**Issue by coderdavi** [godruoyi/php-snowflake#21]
I refer to the documentation ,but it comes to 
Call to undefined method Illuminate\\Support\\Facades\\Cache::store()
how to  resolve it?

**Comment by godruoyi** [comment]
In lumen, You can use it like this.

And please update your php-snowflake to **version 1.1.1** . 

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Godruoyi\Snowflake\Snowflake;
use Godruoyi\Snowflake\LaravelSequenceResolver;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('snowflake', function () {
            return (new Snowflake())
                ->setStartTimeStamp(strtotime('2019-10-10')*1000)
                ->setSequenceResolver(new LaravelSequenceResolver(\Illuminate\Support\Facades\Cache::store()));
        });
    }
}
```

**Comment by coderdavi** [comment]
> In lumen, You can use it like this.
> 
> And please update your php-snowflake to **version 1.1.1** .
> 
> ```
> <?php
> 
> namespace App\Providers;
> 
> use Illuminate\Support\ServiceProvider;
> use Godruoyi\Snowflake\Snowflake;
> use Godruoyi\Snowflake\LaravelSequenceResolver;
> 
> class AppServiceProvider extends ServiceProvider
> {
>     /**
>      * Register any application services.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->app->singleton('snowflake', function () {
>             return (new Snowflake())
>                 ->setStartTimeStamp(strtotime('2019-10-10')*1000)
>                 ->setSequenceResolver(new LaravelSequenceResolver(\Illuminate\Support\Facades\Cache::store()));
>         });
>     }
> }
> ```
I appreciate your helping me

**Comment by godruoyi** [comment]
Hi, @nmfzone, good question, thank you point out.

Currently, this package is a simple implementation. it's not required ZK, you can install/use it in your projects.

but to be careful, we use the Random Algorithm to get snowflake ID by default, so it may cause the generated IDs to be the same, and if you want to generate unique IDs, using SequenceResolver may be a good choice.
