### ISSUE TITLE
可以设置长度吗？生成的编号大于第三方接口最大长度，所以想减少2位

### ISSUE THREAD

**Issue by pasawu** [godruoyi/php-snowflake#22]
可以设置长度吗？生成的编号大于第三方接口最大长度，所以想减少2位

**Comment by godruoyi** [comment]
雪花算法的这个实现是不支持设置长度的。这是算法本身导致的，随着时间差愈来愈大，生成的 ID 也会愈来愈长，最长好像是 19 位。

**Comment by IceBay** [comment]
开始时间设置到近期可以生成较短的编号，不过需要注意随时间推移而增长的设定。
