### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ren-jimmy** [godruoyi/php-snowflake#23]
datacenter AND workerid will be NULL，Will cause duplicate id to be generated in the for loop

![image](https://user-images.githubusercontent.com/25098996/128999921-1f66ac36-a4e8-429b-aafd-10f847799276.png)
![image](https://user-images.githubusercontent.com/25098996/128999883-985e8fd6-cc7f-4387-8e3a-4a8df8a3e24d.png)

**Comment by godruoyi** [comment]
Can you paste the code for the for loop?

**Comment by godruoyi** [comment]
The following tests is passed, maybe it's can help you.

```php
    public function testForeach()
    {
        $snowflake = new Snowflake();
        $datas = [];
        for ($i = 0; $i < 10000; ++$i) {
            $id = $snowflake->id();
            $datas[$id] = 1;
        }

        static::assertTrue(10000 === \count($datas));
    }
```

![image](https://user-images.githubusercontent.com/16079222/129306722-db601dc9-21d6-46a4-abb5-051f616f9188.png)

**Comment by ren-jimmy** [comment]
if this wirte?

        $datas = [];
        for ($i = 0; $i < 10000; ++$i) {
            $id = (new Snowflake())->id();
            $datas[$id] = 1;
        }

**Comment by godruoyi** [comment]
You should ensure that you use the same instance. 

```
 $datas = [];
 $instance = new Snowflake();

    for ($i = 0; $i < 10000; ++$i) {
        $id = $instance->id();
        $datas[$id] = 1;
    }
```

**Comment by ren-jimmy** [comment]
if have more backend script and none set $datacenter $workerid ，they generate id repeat？

**Comment by ren-jimmy** [comment]
改成这样了
![image](https://user-images.githubusercontent.com/25098996/129313076-ec42fd0a-4502-42d5-b57d-a6eb9eb6644d.png)

**Comment by godruoyi** [comment]
Datacenter ID and worker ID is not necessary, You don't need to change it at all.

Readme:

> So if you want use the snowflake algorithm to generate unique ID, You must ensure: The sequence-number generated in the same millisecond of the same node is unique. Based on this, we created this package and integrated multiple sequence-number providers into it.

#13
