### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by seabasss** [godruoyi/php-snowflake#29]
Thanks for this package!

I'm just trying it out with Laravel and I get this when I use the `attach()` function:
`SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value`

Any ideas? Thank you!

**Comment by godruoyi** [comment]
It's my pleasure.

Can you show me your code and how to call it.

**Comment by godruoyi** [comment]
If you have no other question, I will close this issues.

**Comment by seabasss** [comment]
$user->roles()->attach($roleId);

I tried to add snowflake id’s to pivot tables, but if it’s not possible I’ll skip it.

**Comment by godruoyi** [comment]
Maybe your pivot table ID column is not auto increment, and the attach method you can reference this document. https://laravel.com/docs/9.x/eloquent-relationships#attaching-detaching

**Comment by seabasss** [comment]
Yes I understand that, but I was trying to have snowflake id’s on the pivot table and adding a model and the snowflake class didn’t work.

It’s fine, I’ll skip snowflake id’s for pivots.
