### ISSUE TITLE
DEFAULT HANDLER - Error(code:0): Class 'Godruoyi\Snowflake\swoole_lock' not found

### ISSUE THREAD

**Issue by ctfang** [godruoyi/php-snowflake#3]
DEFAULT HANDLER - Error(code:0): Class 'Godruoyi\Snowflake\swoole_lock' not found

**Comment by ctfang** [comment]
fix $this->lock = new \swoole_lock(SWOOLE_MUTEX);

**Comment by godruoyi** [comment]
see pr
