### ISSUE TITLE
Why do I generate snowflake IDs the same when I put them in the for loop

### ISSUE THREAD

**Issue by hyyky** [godruoyi/php-snowflake#47]
Why do I generate snowflake IDs the same when I put them in the for loop
![image](https://user-images.githubusercontent.com/50724513/233577085-cd767086-0f33-4bce-b180-5258e09d6ba3.png)
![image](https://user-images.githubusercontent.com/50724513/233577152-d4bd5558-3ab6-4d7b-9145-1a8d3023378f.png)
![image](https://user-images.githubusercontent.com/50724513/233577319-b675343b-7287-4913-b3e0-736c358b340f.png)

**Comment by godruoyi** [comment]
hi @hyyky  thank you for your interest in this project. Actually, the default RandomSequenceResolver cannot guarantee that the generated ID is unique. You may want to try using FileLockResolver or something else instead.

**Comment by godruoyi** [comment]
@hyyky any updates?

**Comment by godruoyi** [comment]
Close since there are no any updates.
