### ISSUE TITLE
ability to get id as int, instead of string

### ISSUE THREAD

**Issue by the-eater** [godruoyi/php-snowflake#49]
Currently you can only get it as string, causing the id as an int to get transformed into a string, then back into an int again

**Comment by godruoyi** [comment]
Yes, originally we could return an int, but considering that the returned number might be large and could result in loss of precision in some cases, so we changed it to a string type.

**Comment by the-eater** [comment]
Yea, I think I would like it if it's possible to still have that option, be it via `->idInt()` or `->id(int: true)`

e.g. the case of loss of precision should only happen in the following cases: (feel free to correct me if wrong)

- Math that involves floating point operations
- Transforming into JSON
- Being on a 32-bit platform[^1]

But e.g. my use case is storing it in the database, for which it doesn't need to be turned into a string, and since the sign is not used, there's no loss of that either

I am open to making a PR for supporting this, but just making this out of the blue because of a feature I was missing felt a bit over the top, so I made this issue

[^1]: Since all logic is applied to an int, this library actually can't run on 32-bit platforms, and would like cause weird issues

**Comment by godruoyi** [comment]
> just making this out of the blue because of a feature I was missing felt a bit over the top

I appreciate your words. It's clear that you have a deep understanding of open source.

Your proposal is good, but since we have already returned a String type, I think it would be better to implement the intID feature in the Client because it's simple and the caller can convert it to an int type using the following method.

```php
$stringID = $snowflake->id();

$intID = $stringID | 0;
```

Let me know your thoughts //

**Comment by godruoyi** [comment]
No updates received for over a month, close it now, If there are any other issues, please reopen.
