### ISSUE TITLE
Add machineId to the Redis/Laravel sequence generator keys

### ISSUE THREAD

**Issue by simivar** [godruoyi/php-snowflake#50]
Currently, the key for cache entries in `LaravelSequenceResolver` and `RedisSequenceResolver` is just the current time as integer. If the Redis instance is share between machines it would mean that each of the machines would use the same cache entries leading to limitation of 256 unique ids per millisecond per all machines rather than 256 unique ids per machine. 

What do you think about prefixing it with the `machineId` in case of Sonyflake and `datacenter` and `workerId` in case of Snowflake?

**Comment by godruoyi** [comment]
thank you @simivar, you are right, if we use Sonyflake, this will limit all machines to generate only 255 unique IDs per millisecond, while with Snowflake it is 4095.

Are you interested in creating a pull request to fix it?

I don't want to change the signature of the SequenceResolver interface, I plan to do it this way, if you have a better method, please let me know.

1. Add getWorkID getMachineID to Snowflake, maybe we don't need these two methods
2. add the setCachePrefix method to LaravelSequenceResolver
3. Next we can call like this
```php
$snowflake = new \Godruoyi\Snowflake\Snowflake($datacenterId, $workerId);
$redisResilver = (new RedisSequenceResolver($redis))->setCachePrefix("{$datacenterId}-{$workerId}")
$snowflake->setSequenceResolver($redisResilver);

$id = $snowflake->id();
```

Let me know your thoughts. ///

**Comment by simivar** [comment]
I've created #51
