### ISSUE TITLE
Drop unsupported PHP version & add typehints

### ISSUE THREAD

**Issue by simivar** [godruoyi/php-snowflake#52]
As you probably know, PHP no longer actively supports versions below 8.1 ([reference](https://www.php.net/supported-versions.php)). I wonder if you would be open to dropping support for everything lower than 8.1 and releasing a new major version with PHP built-in type-hints added to every method and interface. 

As this is a major change it would require a new version release (3.x). With this change, we could bundle other breaking changes if you are looking into doing any of them.

**Comment by godruoyi** [comment]
Yes, I also think supporting PHP8.1 as default version is a great attempt. We can use many new features in PHP 8.1 and take this opportunity to remove deprecated methods such as getCurrentMicrotime. I think we can do a lot of interesting things, Let's get start.

**Comment by simivar** [comment]
@godruoyi I've opened #54, please review :)

**Comment by godruoyi** [comment]
Wow, that's amazing work! Thank you, @simivar. I will review it today.
