### ISSUE TITLE
2台机器，同时循环1万次，大概有400条是重复生成的

### ISSUE THREAD

**Issue by fxxph** [godruoyi/php-snowflake#6]
2台机器，除了workId不一致，其他都是一样
比如都循环1万次，分别放置文件1.txt 和文件2.txt
单个文件sort 后没问题，还是1万条
但是合并后，在去重，显示19200+条，大概重复了400条，在线等，如何解决~~

**Comment by godruoyi** [comment]
这个问题可能是默认的序列号生成器在每次调用的时候都初始化的问题。

我刚刚提交了个版本，重新编写了测试用例，设置相同的数据中心ID，不同的 workid，测试结果是 OK 的。

你试着更新下版本再试试呢。

https://github.com/godruoyi/php-snowflake/commit/01dac8b1de7627485a05a6ce4156729e880f90bd

**Comment by fxxph** [comment]
好的，多谢，我本地在试一下，稍后回复你

**Comment by fxxph** [comment]
我本地尝试了，目前多条不重复了。
但是单台偶尔可能会出现重复。。。

**Comment by godruoyi** [comment]
你是什么操作出现的重复呢 ，能贴下你测试的代码不？

**Comment by fxxph** [comment]
DeferServiceProvider.php文件中

`if (class_exists('\Godruoyi\Snowflake\Snowflake')) {
            $this->app->singleton('SnowflakeService', function () {
                return (new Snowflake(NUll, crc32(config('app.server_host_name')) % 31))
                    ->setStartTimeStamp(strtotime('2019-08-08') * 1000)
                    ->setSequenceResolver(new LaravelSequenceResolver($this->app->get('cache')->store()));
            });
        }`


app/Http/Controllers/TestController.php文件中调用
$res[] = (int)app('SnowflakeService')->id();

**Comment by godruoyi** [comment]
redis sequence resolver 设置的 key 的过期时间太小（1毫秒），导致可能存在重复的序列号生成。

我已经把默认的过期时间设置为 1 秒。目前测试循环 2w 遍无重复记录产生。

ps: 需要更新版本至  1.0.8

**Comment by fxxph** [comment]
好嘞，我再试试，感谢感谢。

**Comment by godruoyi** [comment]
怎么样，还有其他问题没得呀

**Comment by jiawei666** [comment]
> redis sequence resolver 设置的 key 的过期时间太小（1毫秒），导致可能存在重复的序列号生成。
> 
> 我已经把默认的过期时间设置为 1 秒。目前测试循环 2w 遍无重复记录产生。
> 
> ps: 需要更新版本至 1.0.8

我也遇到过这个问题，为什么过期时间短会造成redis出错呢？我发现这种情况下，redis会出现某些值的ttl是-1

**Comment by godruoyi** [comment]
> > redis sequence resolver 设置的 key 的过期时间太小（1毫秒），导致可能存在重复的序列号生成。
> > 我已经把默认的过期时间设置为 1 秒。目前测试循环 2w 遍无重复记录产生。
> > ps: 需要更新版本至 1.0.8
> 
> 我也遇到过这个问题，为什么过期时间短会造成redis出错呢？我发现这种情况下，redis会出现某些值的ttl是-1

是这样的，当两个请求同一时刻到达时（相同的 $currentTime），若一个请求执行较慢，当他执行到这个方法时，前面的设置的过期时间已到期，这将导致两个请求得到相同的序列号 0，从而得到重复的 ID。

```
    public function sequence(int $currentTime)
    {
        $lua = "return redis.call('exists',KEYS[1])<1 and redis.call('psetex',KEYS[1],ARGV[2],ARGV[1])";

        if ($this->redis->eval($lua, [($key = $this->prefix.$currentTime), 1, 1000], 1)) {
            return 0;
        }

        return $this->redis->incrby($key, 1);
    }
```

希望对你有所帮助。
