### ISSUE TITLE
每次运行生成的id求余32都等于0

### ISSUE THREAD

**Issue by zhoulin1359** [godruoyi/php-snowflake#7]
$snowflake = new \Godruoyi\Snowflake\Snowflake;

echo $snowflake->id() % 32; //0

**Comment by godruoyi** [comment]
出现这个问题的原因如下：

目前我们设置的序列号的长度是 12 位，若你每次都是这样调用的

```php
$snowflake = new \Godruoyi\Snowflake\Snowflake;

echo $snowflake->id();
```

那生成的 ID 解析出来，序列号为 0，然后我们在构建完整的雪花 ID 的时候，最起码会将其他参数左移 12 位：

![image](https://user-images.githubusercontent.com/16079222/70884017-adc21f00-200f-11ea-901f-6eec0e13ab55.png)

最后用 32 求余肯定后一直为 0.

> 最后为什么会用 32 来求余呢，这是解决什么问题啊。

**Comment by han8gui** [comment]
场景：利用雪花算法生成帖子ID，再给帖子ID分表
可以加随机数来解决吗？

**Comment by godruoyi** [comment]
我不明白你是想用随机数来解决什么呢❓

**Comment by han8gui** [comment]
> 我不明白你是想用随机数来解决什么呢❓

目的：根据帖子ID分表
方案：通过截断10位长度来分表了。
