### ISSUE TITLE
snowflake-7.lock is not a valid lock file.

### ISSUE THREAD

**Issue by jkaltopp** [godruoyi/php-snowflake#70]
snowflake-7.lock is not a valid lock file. 报错是什么问题？

**Comment by godruoyi** [comment]
Could you please delete the invalid JSON file and try again? see https://github.com/godruoyi/php-snowflake/blob/0193ef3464570c4470d83163c0a605983ad6b9d9/src/FileLockResolver.php#L85

**Comment by jkaltopp** [comment]
已经删除，请问什么情况会出现这样的问题

**Comment by godruoyi** [comment]
Hmm, I'm not sure. Have you manually edited this file or made any recent changes? If so, please inform me. Maybe we can work together to figure out the reason behind it.

**Comment by godruoyi** [comment]
Hey @jkaltopp, did the same issue occur again after you deleted the lock file?

**Comment by godruoyi** [comment]
closed since there are no any updates more that 3 months
