### ISSUE TITLE
ID位数

### ISSUE THREAD

**Issue by lanrenbulan** [godruoyi/php-snowflake#75]
设置不同的开始时间，生成的ID位置可能是18位，可能是19位，而且看某些平台都是1开头的19位，这是在18位上加了一个前导1？

**Comment by godruoyi** [comment]
算法并没有做额外的处理，如果当前时间和你设置的开始时间的差值越大，生成的 ID 就越大。生成的最终 ID 不确定是 18/19 位，这是由生成雪花算法的各部分共同组成的，你可以参考下这个 https://github.com/godruoyi/php-snowflake/issues/9#issue-582254799
