### ISSUE TITLE
Why set a starting timestamp

### ISSUE THREAD

**Issue by calebdw** [godruoyi/php-snowflake#76]
Hello!

I'm trying to integrate this into my Laravel application and I had some questions surrounding setting the starting timestamp:

- First and foremost, why would the starting timestamp be set to anything other than the Unix epoch (1970-01-01 00:00:00 Z)? This would be the most intuitive date and is generally what a timestamp is assumed to be based on.
- Should I set my own starting timestamp or just leave the default? What are the implication of one over the other?
- It seems like the default timestamp use is `2019-08-08 08:08:08` which is seemingly random?

Thanks!

**Comment by godruoyi** [comment]
Hi @calebdw, thank you for your interest in this package. Let me try to answer your questions:

1. Setting the start time to the Unix epoch (1970-01-01 00:00:00 Z) is a good choice, but it's important to note that the Snowflake algorithm can only function properly for up to 69 years. If we set the start time to 1970, it means that by 2030 all programs using the default start time will become incompatible.
3. I recommend selecting a later start time for your project(like 2020 or something else), as this will extend the lifespan of the Snowflake algorithm.
4. Yes, it is random and you can choose any value you prefer.

Lastly, thank you for your question. If we don't consider the lifespan of the snowflake algorithm, I genuinely believe that setting the Unix epoch as the default start time is a solid choice.

**Comment by calebdw** [comment]
Ahh, sounds good, thanks!
