### ISSUE TITLE
如何使生成的ID长度小一点呢？

### ISSUE THREAD

**Issue by hellowords** [godruoyi/php-snowflake#9]
首先感谢作者提供这么方便的包！

今天遇到了一个问题，后台生成的ID长度太大了，传递给前端之后，js因为数值太大失去了精度。请问修改什么配置能减小生成ID的长度

**Comment by godruoyi** [comment]
我们知道，雪花算法是由 1 + 41 + 5 + 5 + 12 = 64 位二进制组成的，最终将这些二进制转化为 16 进制得到雪花 ID。

![file](https://images.godruoyi.com/logos/201908/13/_1565672621_LPW65Pi8cG.png)

1. 最高位固定设置为 0
2. 第二部分表示当前时间 - 固定开始时间的毫秒值
3. 第三第四部分表示数据中心 ID 和机器 ID
4. 最后位为随机的序列号

现在我们要生成一个长度相对小一点的数；想象一下，将各部位设置为 0，生成的数不就最小了吗？

![image](https://user-images.githubusercontent.com/16079222/76817510-00dd8500-683e-11ea-9156-bdc9a6fed94c.png)

在转为 16 进制，为 0。

```bash
✗ psysh
Psy Shell v0.9.8 (PHP 7.3.14 — cli) by Justin Hileman
New version is available (current: v0.9.8, latest: v0.10.0)
>>>
>>>bindec("000000000000000000000000000000000000000000000000000000000000000")
=> 0
>>>
```

也就是说，将各部分都设置为 0，得到的雪花 ID 将没有任何意义；并且我们也不可能设置每个部分都为 0。

现在我们把时间差设置为 2 毫秒，数据中心 ID 和机器 ID 都设置为 1，再试试：

![image](https://user-images.githubusercontent.com/16079222/76817544-210d4400-683e-11ea-96ad-cf5fe8529db9.png)

转为十进制得到的雪花 ID 为：

```bash
✗ psysh
Psy Shell v0.9.8 (PHP 7.3.14 — cli) by Justin Hileman
New version is available (current: v0.9.8, latest: v0.10.0)
>>>
>>> bindec("0000000000000000000000000000000000000000100000100001000000000000")
=> 8523776
>>>
```

所以，要想得到一个相对小的 ID，我们需要确保时间戳的差值相对较小，并手动设置数据中心 ID 和机器 ID。

```php

// 目前 sdk 不支持设置数据中心 ID 和机器 ID 为 0，若设置为 0，将随机一个 mt_rand(0, 31) 的数
$snowflake = new \Godruoyi\Snowflake\Snowflake(1, 1);
$snowflake->setStartTimeStamp(strtotime('2020-03-09')*1000);

$snowflake->id();
```

前端精度的问题，你可以直接转为 string 类型的数值后，在给他们用，就不存在精度丢失啦。

PS:

那雪花算法能生成的最大 ID 是多少呢？如下，将各部分设置为最大值，得到的额 ID 肯定也是最大了。

![image](https://user-images.githubusercontent.com/16079222/76817561-2ec2c980-683e-11ea-9450-124ca97f7cac.png)

转为十进制得到的雪花 ID 为：

```bash
✗ psysh
Psy Shell v0.9.8 (PHP 7.3.14 — cli) by Justin Hileman
New version is available (current: v0.9.8, latest: v0.10.0)
>>>
>>> bindec("0111111111111111111111111111111111111111111111111111111111111111")
=> 9223372036854775807
>>>
```

> 41 个 1 组成的二进制转为 16 进制得到时间差的毫秒数，转化为 年 为：

```bash
>>> bindec("11111111111111111111111111111111111111111")
=> 2199023255551
>>> 2199023255551 / (24 * 60 * 60 * 1000 * 365)
=> 69.730570000983
```

所以雪花算法最多能正常工作 69 年，这就是为什么要尽量设置一个比较大的开始时间的由来。

希望你能明白算法的具体由来，这样使用起来就清晰多了，是吧。😀😀😀

**Comment by hellowords** [comment]
@godruoyi 感谢你的用心回复，读完阁下的解释真是醍醐灌顶！谢谢
